const quotes = [
  { quote: 'Jeff Dean proved that P=NP when he solved all NP problems in polynomial time on a whiteboard.', author: 'Unknown' },
  { quote: "Jeff Dean's PIN is the last 4 digits of pi.", author: 'Unknown' },
  { quote: "When Jeff gives a seminar at Stanford, it's so crowded Don Knuth has to sit on the floor. (**TRUE**)", author: 'Unknown' },
  { quote: 'Jeff Dean once bit a spider, the spider got super powers and C++ readability.', author: 'Unknown' },
  { quote: 'Once, in early 2002, when the index servers went down, Jeff Dean answered user queries manually for two hours. Evals showed a quality improvement of 5 points.', author: 'Unknown' },
  { quote: 'Jeff Dean got promoted to level 11 in a system where max level is 10. (**TRUE**)', author: 'Unknown' },
  { quote: "Google Search was Jeff Dean's Noogler Project.", author: 'Unknown' },
  { quote: 'Jeff Dean has punch card readability.', author: 'Unknown' },
  { quote: 'Jeff Dean puts his pants on one leg at a time, but if he had more than two legs, you would see that his approach is actually `O(log n)`.', author: 'Unknown' },
  { quote: 'Jeff Dean acquired Sawzall readability after writing 58 lines of Sawzall code. As part of his readability review, he pointed out a flaw in the style guide which was promptly corrected by the reviewer.', author: 'Unknown' },
  { quote: "Sanjay once asked Jeff Dean if he could keep the entire web in his memory. Due to the noise from his keyboard cooling fan, Jeff Dean misheard slightly and wrote Mustang instead of simply answering 'Yes'.", author: 'Unknown' },
  { quote: 'Jeff Dean compiles and runs his code before submitting, but only to check for compiler and CPU bugs.', author: 'Unknown' },
  { quote: "Unsatisfied with constant time, Jeff Dean created the world's first `O(1/n)` algorithm.", author: 'Unknown' },
  { quote: 'Jeff Dean has binary readability.', author: 'Unknown' },
  { quote: 'Jeff Dean has binary writability.', author: 'Unknown' },
  { quote: 'When Jeff Dean goes on vacation, production services across Google mysteriously stop working within a few days. This is actually true.', author: 'Unknown' },
  { quote: 'Jeff Dean once shifted a bit so hard it ended up on another computer.', author: 'Unknown' },
  { quote: "During his own Google interview, Jeff Dean was asked the implications if P=NP were true. He said 'P = 0 or N = 1.' Then, before the interviewer had even finished laughing, Jeff examined Google's public certificate and wrote the private key on the whiteboard.", author: 'Unknown' },
  { quote: "You use 10% of your brain. The other 90% is running one of Jeff's mapreduce jobs.", author: 'Unknown' },
  { quote: "Jeff Dean's resume lists the things he hasn't done; it's shorter that way.", author: 'Unknown' },
  { quote: "To Jeff Dean, 'NP' means 'No Problemo'.", author: 'Unknown' },
  { quote: 'Jeff Dean wrote an `O(n^2)` algorithm once. It was for the Traveling Salesman Problem.', author: 'Unknown' },
  { quote: "You don't explain your work to Jeff Dean. Jeff Dean explains your work to you.", author: 'Unknown' },
  { quote: "Jeff Dean's resume has so many accomplishments, it has a table of contents.", author: 'Unknown' },
  { quote: 'Jeff Dean was forced to invent asynchronous APIs one day when he optimized a function so that it returned before it was invoked.', author: 'Unknown' },
  { quote: 'The rate at which Jeff Dean produces code jumped by a factor of 40 in late 2000 when he upgraded his keyboard to USB2.0.', author: 'Unknown' },
  { quote: 'When Jeff Dean designs software, he first codes the binary and then writes the source as documentation.', author: 'Unknown' },
  { quote: "Jeff Dean's Peer Review is what got Larry promoted to CEO.", author: 'Unknown' },
  { quote: "When God said: 'Let there be light!', Jeff Dean was there to do the code review.", author: 'Unknown' },
  { quote: 'When Graham Bell invented the telephone, he saw a missed call from Jeff Dean', author: 'Unknown' },
  { quote: "Compilers don't warn Jeff Dean. Jeff Dean warns compilers.", author: 'Unknown' },
  { quote: "Jeff Dean doesn't exist, he's actually an advanced AI created by Jeff Dean.", author: 'Unknown' },
  { quote: "Jeff Dean's IDE doesn't do code analysis, it does code appreciation.", author: 'Unknown' },
  { quote: "Jeff Dean doesn't use ECC memory. He anticipates cosmic rays and uses them to improve performance.", author: 'Unknown' },
  { quote: 'Jeff Dean once failed a Turing test when he correctly identified the 203rd Fibonacci number in less than a second.', author: 'Unknown' },
  { quote: 'Jeff Dean invented Bigtable so that he would have a place to send his weekly snippets.', author: 'Unknown' },
  { quote: 'On the zeroth day, Jeff Dean created God.', author: 'Unknown' },
  { quote: "Jeff Dean once implemented a web server in a single printf() call. Other engineers added thousands of lines of explanatory comments but still don't understand exactly how it works. Today that program is known as Google Web Server.", author: 'Unknown' },
  { quote: 'When Jeff has an ergonomic evaluation, it is for the protection of his keyboard.', author: 'Unknown' },
  { quote: 'Jeff Dean can beat you at connect four. In three moves.', author: 'Unknown' },
  { quote: 'Jeff Dean invented BigTable because his resume was too big to fit anywhere else.', author: 'Unknown' },
  { quote: "Jeff Dean took the bite out of Apple's logo.", author: 'Unknown' },
  { quote: 'Chuck Norris can kill you. Jeff Dean can `kill -9` you.', author: 'Unknown' },
  { quote: 'Jeff Dean can parse HTML with a regular expression...correctly.', author: 'Unknown' },
  { quote: 'When Jeff has trouble sleeping, he MapReduces sheep.', author: 'Unknown' },
  { quote: 'When Jeff Dean fires up the profiler, loops unroll themselves in fear.', author: 'Unknown' },
  { quote: "When your code has undefined behavior, you get a seg fault and corrupted data. When Jeff Dean's code has undefined behavior, a unicorn rides in on a rainbow and gives everybody free ice cream.", author: 'Unknown' },
  { quote: "Jeff doesn't sleep, he just sends SIGSUSPEND to the universe.", author: 'Unknown' },
  { quote: 'Jeff got Java readability with only 8 lines of code.', author: 'Unknown' },
  { quote: 'Jeff Dean can instantiate abstract classes.', author: 'Unknown' },
  { quote: '`gcc -O4` sends your code to Jeff Dean for a complete rewrite.', author: 'Unknown' },
  { quote: "Jeff can recite 20,000 digits of pi in 5 hours. He doesn't remember them; he just recomputes them on the fly using only `O(log n)` space.", author: 'Unknown' },
  { quote: 'Jeff Dean remembers only one password. For each site, he concatenates it with the site name, computes its SHA-256 hash, and then types the result.', author: 'Unknown' },
  { quote: 'Jeff Dean is still waiting for mathematicians to discover the joke he hid in the digits of pi.', author: 'Unknown' },
  { quote: "There is no `Ctrl` key on Jeff Dean's keyboard. Jeff Dean is always in control.", author: 'Unknown' },
  { quote: 'Jeff Dean was born on December 31, 1969 at 11:48 PM. It took him twelve minutes to implement his first time counter.', author: 'Unknown' },
  { quote: "When Jeff Dean says 'Hello World', the world says 'Hello Jeff'.", author: 'Unknown' },
  { quote: 'Jeff Dean can get 1s out of `/dev/zero`.', author: 'Unknown' },
  { quote: 'Jeff Dean simply walks into Mordor.', author: 'Unknown' },
  { quote: 'Jeff Dean spent some 20% time on an AI project. That produced Urs Hoelzle.', author: 'Unknown' },
  { quote: 'Google once had to move out of a datacenter after Jeff Dean accidentally compressed the index so densely that a black hole was formed.', author: 'Unknown' },
  { quote: 'Jeff starts his programming sessions with `cat > /dev/mem`.', author: 'Unknown' },
  { quote: 'The speed of light in a vacuum used to be about 35 mph. Then Jeff Dean spent a weekend optimizing physics.', author: 'Unknown' },
  { quote: "When Jeff Dean sends you a code review, it's because he thinks there's something in it you should learn.", author: 'Unknown' },
  { quote: 'Jeff Dean does not `sleep()`, he `wait()`s.', author: 'Unknown' },
  { quote: 'Jeff Dean invented MapReduce so he could sort his fan mail.', author: 'Unknown' },
  { quote: 'Once Jeff Dean ordered a list, and the list obeyed him.', author: 'Unknown' },
  { quote: "Chuck Norris is Jeff Dean's 20% project.", author: 'Unknown' },
  { quote: 'When your code is killed by SIGJEFF, it never runs again.', author: 'Unknown' },
  { quote: "Jeff Dean's calendar goes straight from March 31st to April 2nd; no one fools Jeff Dean.", author: 'Unknown' },
  { quote: 'Jeff Dean never has the wrong number; you have the wrong phone.', author: 'Unknown' },
  { quote: 'Jeff Dean has exactly two keys on his keyboard: `0` and `1`.', author: 'Unknown' },
  { quote: 'Errors treat Jeff Dean as a warning.', author: 'Unknown' },
  { quote: 'Cricket matches used to take 5 days, until Jeff optimized them.', author: 'Unknown' },
  { quote: "Jeff Dean's watch displays seconds since January 1st, 1970. He is never late.", author: 'Unknown' },
  { quote: "Jeff's code is so fast the assembly code needs three HALT opcodes to stop it.", author: 'Unknown' },
  { quote: "Emacs' preferred editor is Jeff Dean.", author: 'Unknown' },
  { quote: "Google: it's basically a Jeff Dean's side project.", author: 'Unknown' },
  { quote: 'Jeff Dean has to unoptimize his code so that reviewers believe it was written by a human.', author: 'Unknown' },
  { quote: 'Websearch is just a large unittest Jeff wrote for his real app.', author: 'Unknown' },
  { quote: "Jeff Dean doesn't need speakers or headphones. He just types `cat *.mp3`, glances at the screen, and his brain decodes the music in the background while he works.", author: 'Unknown' },
  { quote: 'Jeff Dean has Perl Readability. (**TRUE**)', author: 'Unknown' },
  { quote: 'Jeff Dean quicksorts his laundry.', author: 'Unknown' },
  { quote: 'The OR ELSE construct had to be removed from ISO C after Jeff Dean used it in Mustang and kernels started panicking in terror.', author: 'Unknown' },
  { quote: 'Jeff Dean is not afraid of evil constructors. They are afraid of him.', author: 'Unknown' },
  { quote: "Jeff Dean doesn't write bugs, just features you are unable to understand.", author: 'Unknown' },
  { quote: "Jeff Dean eschews both Emacs and VI. He types his code into `zcat`, because it's faster that way.", author: 'Unknown' },
  { quote: 'When Jeff Dean sends an Ethernet frame, there are no collisions because the competing frames retreat back up into the buffer memory on their source network cards.', author: 'Unknown' },
  { quote: 'Jeff once simultaneously reduced all binary sizes by 3% and raised the severity of a previously known low-priority Python bug to critical-priority in a single change that contained no Python code.', author: 'Unknown' },
  { quote: 'One day, Jeff Dean grabbed his Etch-a-Sketch instead of his laptop on his way out the door. On his way back home to get his real laptop, he programmed the Etch-a-Sketch to play Tetris.', author: 'Unknown' },
  { quote: "The x86-64 spec includes several undocumented instructions marked private use. They are actually for Jeff Dean's use.", author: 'Unknown' },
  { quote: 'Knuth mailed a copy of <u>The Art of Computer Programming</u> to Google. Jeff Dean autographed it and mailed it back.', author: 'Unknown' },
  { quote: "When he heard that Jeff Dean's autobiography would be exclusive to the platform, Richard Stallman bought a Kindle.", author: 'Unknown' },
  { quote: 'Jeff Dean can losslessly compress random data.', author: 'Unknown' },
  { quote: "When asked if the facts about him are true, Jeff Dean responded with '111111'. While the interviewer was still trying to figure out what he meant, he clarified, 'every single bit of it is true.'", author: 'Unknown' },
  { quote: 'Jeff Dean mines bitcoins. In his head.', author: 'Unknown' },
];

module.exports = quotes;
